### ISSUE TITLE
Cannot use `addUser` because it is not in the path

### ISSUE THREAD

**Issue by chipironcin** [bitnami/nami-utils#34]
While deploying bitnami/bitnami-docker-nginx container in Pivotal CloudFoundry, an error appeared during installation of the Nami Module:

>Error executing 'postInstallation': Don't know how to add group `nginx` on this strange linux

After a bit of research, me and @prydonius found that commands `userAdd` or `addUser` were not present in the PATH.
It seems Pivotal CloudFoundry makes a few modifications to the environment to make it more secure, so:
`PATH=/bin:/usr/bin`
But `addUser` or `userAdd` are in `/usr/sbin`

Nami should take these restricted environments into account and make sure the PATH variable includes paths to most system binaries.

This is also related to bitnami/bitnami-docker-nginx#58 where the binary `nami` cannot be found.

**Comment by juamedgod** [comment]
Fixed in https://github.com/bitnami/nami-utils/commit/19b2ce7d94b3f1a354cfd3ff747ba9115a5796b5
